fix ci v1.9

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -1,6 +1,9 @@
 name: Playwright E2E Tests
 
 on:
+  push:
+    branches:
+      - '**'
   pull_request:
     branches:
       - develop
@@ -10,6 +13,7 @@ jobs:
   test:
     name: Run E2E Tests
     runs-on: ubuntu-latest
+    environment: .env
 
     steps:
       - name: Checkout repository
@@ -32,6 +36,17 @@ jobs:
           pip install playwright
           playwright install --with-deps chromium
 
+      - name: Diagnostic Step (Check Secret Presence)
+        env:
+          CHECK_URL: ${{ secrets.STG_URL }}
+        run: |
+          if [ -z "$CHECK_URL" ]; then
+            echo "❌ ERROR: GitHub Actions does NOT see STG_URL secret!"
+            exit 1
+          else
+            echo "✅ SUCCESS: GitHub Actions successfully loaded STG_URL."
+          fi
+
       - name: Run Playwright Tests
         env:
           STG_URL: ${{ secrets.STG_URL }}
@@ -41,7 +56,6 @@ jobs:
           SIMPLE_USER_PASSWORD: ${{ secrets.SIMPLE_USER_PASSWORD }}
           HEADLESS: "true"
           PYTHONPATH: ${{ github.workspace }}
-
         run: |
           pytest TP_Polako_E2E/tests \
             --env stg \
